### ISSUE TITLE
List에 있는 데이터 가지고 올 때 한줄로 줄이기

### ISSUE THREAD

**Issue by Joseph-Cha** [Joseph-Cha/DotNetStudy#5]
커밋한 부분을 여기로 가지고 오고 싶은데 아래 reference로 추가하는 방법 말고는 잘 모르겠습니다 ㅠㅠ 

일단 질문 내용은 생성자를 통해 MbtiInfo 개체를 List로 저장한 다음에 

특정 알파뱃이 포함되어 있을 때 Name값을 가지고 오는 식으로 코드를 짜고 싶습니다.

이것을 한줄의 코드로 짤 수 있는지 궁금합니다!

**Comment by jongfeel** [comment]
pull request로 만들어서 리뷰를 하면 쉽게 됩니다.
commit 내용도 들어가고 추가 코멘트도 달 수 있게 되고요.

다시 pull request로 만들어 보면 어떨까요?

**Comment by Joseph-Cha** [comment]
네 좋습니다!😃
